name: Pull Request Approver

# Controls when the workflow will run
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/auto-approve-action@v2
      if: github.actor == 'BenHall-1'
      with:
        github-token: "${{ secrets.BOT_GITHUB_TOKEN }}"
  add_label:
    runs-on: ubuntu-latest
    needs: auto-approve
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: 'PR: Bot Owner'
