# This is a basic workflow to help you get started with Actions

name: Deploy Translations

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.BOT_SSH_KEY }}
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          submodules: true
      - name: Pull & update submodules recursively
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote
      - name: Commit
        run: |
          git config user.email "github@prosperitybot.net"
          git config user.name "Prosperity Bot - Automation"
          git add --all
          git commit -m "Update submodules" || echo "No changes to commit"
          git branch -M automatic/update-translations
          git checkout automatic/update-translations
          git push -u origin automatic/update-translations
      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
        run: |
          gh pr create --title "🌍 Updated Translations" --body "Pull Request for @prosperitybot/translations" -B main -H automatic/update-translations -l "🌍 Translations" -r "prosperitybot/approvers" -a "@me"
